import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import './style.css';
type Asset={path:string;name:string;type:'image'|'video'};
type Item={id:string;title:string;durationSeconds:number|null;status:'draft'|'review'|'approved';notes:string;assets:Asset[];selectedStart:string|null;selectedEnd:string|null;selectedVideo:string|null};
type Ref={label:string;path:string;type:'image'|'video'|'document';exists:boolean};
type Board={revision:number|string;project:{title:string;sourcePath:string;sourceMarkdown:string;sceneId:string;sceneTitle:string};items:Item[];references:Ref[];updatedAt:string};
const file=(path:string)=>'/api/file?path='+encodeURIComponent(path);
const labels={draft:'準備中',review:'要確認',approved:'採用済み'};
async function api(url:string,options?:RequestInit){const res=await fetch(url,options);const data=await res.json();if(!res.ok)throw new Error(res.status===409?'別の場所で変更されています。編集内容を控えてから「再読込」を選んでください。':data.error||'読み込みに失敗しました');return data;}
function App(){const [board,setBoard]=useState<Board|null>(null),[baseline,setBaseline]=useState(''),[active,setActive]=useState(''),[mode,setMode]=useState('storyboard'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[doc,setDoc]=useState<{path:string;title:string;markdown:string}|null>(null),[viewer,setViewer]=useState<Ref|Asset|null>(null),[history,setHistory]=useState<{id:string;createdAt:string}[]|null>(null),[playing,setPlaying]=useState(false),[playIndex,setPlayIndex]=useState(0);
const [confirmAction,setConfirmAction]=useState<null|(()=>void)>(null),[confirmText,setConfirmText]=useState('');
function ask(text:string,action:()=>void){setConfirmText(text);setConfirmAction(()=>action)}
const dirty=!!board&&JSON.stringify(board.items)!==baseline;const item=board?.items.find(x=>x.id===active);
async function load(){try{const b=await api('/api/board');setBoard(b);setBaseline(JSON.stringify(b.items));setActive(a=>b.items.some((i:Item)=>i.id===a)?a:b.items[0]?.id||'');setError('');}catch(e){setError(String(e));}}
useEffect(()=>{load()},[]);
useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
useEffect(()=>{if(!playing||!board?.items.length)return;const t=setTimeout(()=>{if(playIndex>=board.items.length-1){setPlaying(false)}else setPlayIndex(x=>x+1)},(board.items[playIndex].durationSeconds||3)*1000);return()=>clearTimeout(t)},[playing,playIndex,board]);
useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setViewer(null);setDoc(null);setHistory(null);setConfirmAction(null);setPlaying(false)}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
function edit(p:Partial<Item>){setBoard(b=>b?{...b,items:b.items.map(x=>x.id===active?{...x,...p}:x)}:b);setMessage('')}
async function save(){if(!board)return;setBusy(true);try{const b=await api('/api/board',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:board.revision,items:board.items.map(({id,title,durationSeconds,status,notes,selectedStart,selectedEnd,selectedVideo})=>({id,title,durationSeconds,status,notes,selectedStart,selectedEnd,selectedVideo}))})});setBoard(b);setBaseline(JSON.stringify(b.items));setMessage('ローカルに保存しました');setError('')}catch(e){setError(String(e))}finally{setBusy(false)}}
function move(delta:number){if(!board)return;const items=[...board.items];const n=items.findIndex(x=>x.id===active);if(n+delta<0||n+delta>=items.length)return;[items[n],items[n+delta]]=[items[n+delta],items[n]];setBoard({...board,items})}
async function openDoc(path:string){try{setViewer(null);setPlaying(false);if(path.endsWith('/')){const folder=await api('/api/directory?path='+encodeURIComponent(path));setDoc({path:folder.path.endsWith('/')?folder.path:folder.path+'/',title:'素材フォルダ',markdown:'# 素材フォルダ\n\n'+(folder.entries.length?folder.entries.map((a:{name:string;path:string})=>'- ['+a.name+']('+encodeURI(a.name)+(a.path.endsWith('/')?'/':'')+')').join('\n'):'まだ素材がありません。')});}else setDoc(await api('/api/document?path='+encodeURIComponent(path)))}catch(e){setError(String(e))}}
function resolve(path:string,base:string){try{return decodeURIComponent(new URL(path,'https://local/'+base).pathname.slice(1))}catch{return path}}
function md(text:string,path:string){return <Markdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>{if(!href)return <span>{children}</span>;if(/^https?:\/\//.test(href))return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>;if(href.startsWith('#'))return <a href={href}>{children}</a>;const p=resolve(href,path);return <button className="textlink" onClick={()=>/\.(png|jpg|jpeg|webp|gif)$/i.test(p)?(setDoc(null),setViewer({path:p,name:typeof children==='string'?children:p,type:'image'})):/\.(mp4|webm|mov)$/i.test(p)?(setDoc(null),setViewer({path:p,name:typeof children==='string'?children:p,type:'video'})):openDoc(p)}>{children}</button>},img:({src,alt})=><img className="markdown-image" src={src?.startsWith('http')?src:file(resolve(src||'',path))} alt={alt||''}/>}}>{text}</Markdown>}
if(!board)return <main className="loading"><h1>制作ボード</h1><p>{error||'プロジェクトを読み込んでいます…'}</p><button onClick={load}>再読込</button></main>;
const imageRefs=board.references.filter(r=>r.type==='image'&&r.exists);const completed=board.items.filter(i=>i.status==='approved').length;const preview=board.items[playIndex];
return <div className="app"><aside className="sidebar"><div className="brand"><span className="brand-icon">▦</span> PRODUCTION<br/><small>LOCAL WORKSPACE</small></div><div className="project-caption">PROJECT</div><h2>{board.project.title}</h2><div className="sidebar-rule"/><div className="project-caption">SCENES</div><button className="scene-current" onClick={()=>setMode('storyboard')}><span>07</span><div>{board.project.sceneTitle}<small>制作準備 · {board.items.length} 構成項目</small></div></button><p className="sidebar-note">原作から、ひとつずつ。<br/>確認した素材で物語をつなぐ。</p><div className="local-badge"><i/> ローカル保存<span>GPU 接続なし</span></div></aside>
<div className="workspace"><header className="topbar"><span>制作ボード <span className="separator">/</span> SCENE 07</span><div className="save-tools"><span className={dirty?'unsaved':'muted'}>{dirty?'● 未保存の変更':message||'保存済み'}</span><button onClick={()=>{if(!dirty)load();else ask('未保存の変更を破棄して再読込しますか？',()=>{void load()})}}>再読込</button><button className="primary" disabled={!dirty||busy} onClick={save}>{busy?'保存中…':'変更を保存'}</button></div></header>
{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>閉じる</button></div>}
<section className="heading"><div><p className="eyebrow">STORY TO SCREEN · SCENE 07</p><h1>{board.project.sceneTitle}</h1><p className="subtitle">構成を整え、素材を比べる。次の生成に進むための制作ノート。</p></div><div className="scene-stat"><strong>{String(board.items.length).padStart(2,'0')}</strong><span>構成項目</span><small>{completed} 採用済み</small></div></section>
<div className="toolbar"><nav aria-label="表示モード">{[['storyboard','絵コンテ'],['compare','候補比較'],['readme','README / 原資料']].map(([v,l])=><button className={mode===v?'tab active':'tab'} key={v} onClick={()=>setMode(v)}>{l}</button>)}</nav><button className="quiet" onClick={async()=>{try{setHistory((await api('/api/history')).entries)}catch(e){setError(String(e))}}}>↶ 保存履歴</button></div>
{mode==='readme'?<article className="source-view"><div className="source-title"><span>原資料</span><code>{board.project.sourcePath}</code></div><div className="markdown">{md(board.project.sourceMarkdown,board.project.sourcePath)}</div></article>:<div className="editing-layout"><main className="canvas"><div className="section-label"><span>{mode==='compare'?'REFERENCE & CANDIDATES':'SCENE CONTENTS'}</span><small>原資料の構成項目 · カット分割前</small></div>{mode==='storyboard'?<div className="card-grid">{board.items.map((x,n)=>{const img=x.selectedStart||x.assets.find(a=>a.type==='image')?.path;return <button key={x.id} className={'shot-card '+(active===x.id?'selected':'')} onClick={()=>{setActive(x.id);if(window.innerWidth<=900)document.querySelector('.inspector')?.scrollIntoView({behavior:'smooth',block:'start'})}}><div className="shot-image">{img?<img src={file(img)} alt={x.title}/>:<div className="empty-image"><span>{String(n+1).padStart(2,'0')}</span><small>素材を待っています</small></div>}<span className={'status '+x.status}>{labels[x.status]}</span><span className="duration">{x.durationSeconds===null?'尺 未定':x.durationSeconds+'秒'}</span></div><div className="card-body"><small>CONTENT {String(n+1).padStart(2,'0')}</small><h3>{x.title}</h3><p>{x.notes||'選択して構成・素材を確認'}</p><footer><span>{x.assets.length} 素材</span><span>詳細 ↗</span></footer></div></button>})}</div>:<><label className="compare-select">構成項目<select value={active} onChange={e=>setActive(e.target.value)}>{board.items.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><h3>参照画像</h3><div className="reference-grid">{imageRefs.map(r=><button key={r.path} onClick={()=>setViewer(r)}><img src={file(r.path)} alt={r.label}/><span>{r.label}</span></button>)}</div><h3>候補素材</h3>{item?.assets.length?<div className="reference-grid">{item.assets.map(a=><button key={a.path} onClick={()=>setViewer(a)}>{a.type==='image'?<img src={file(a.path)} alt={a.name}/>:<span className="video-placeholder">▶ 動画</span>}<span>{a.name}</span></button>)}</div>:<div className="empty-state">この項目には、まだ候補素材がありません。<br/><small>既存の素材フォルダに追加後、再読込で反映します。</small></div>}</>}
<section className="references"><div className="section-label"><span>REFERENCE LIBRARY</span><small>既存の参照素材</small></div><div className="ref-tray">{board.references.map(r=><button key={r.path} disabled={!r.exists} title={r.path} onClick={()=>r.type==='document'?openDoc(r.path):setViewer(r)}>{r.type==='image'&&r.exists?<img src={file(r.path)} alt=""/>:<span className="doc-icon">{r.type==='document'?'▤':'▷'}</span>}<span>{r.label}<small>{r.exists?(r.type==='document'?'資料を開く':'拡大して確認'):'ファイルなし'}</small></span></button>)}</div></section></main>
<aside className="inspector">{item?<><div className="section-label"><span>DETAILS</span><small>{item.id}</small></div><h2>構成項目を編集</h2><label>タイトル<input value={item.title} onChange={e=>edit({title:e.target.value})}/></label><div className="field-row"><label>予定尺（秒）<input type="number" min="0.1" step="0.1" placeholder="未定" value={item.durationSeconds??''} onChange={e=>edit({durationSeconds:e.target.value===''?null:Number(e.target.value)})}/></label><label>確認状況<select value={item.status} onChange={e=>edit({status:e.target.value as Item['status']})}>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></div><label>構成・修正メモ<textarea rows={7} value={item.notes} placeholder="動作、台詞、修正したいこと…" onChange={e=>edit({notes:e.target.value})}/></label><h3>採用素材</h3>{([['selectedStart','開始画像','image'],['selectedEnd','終了画像','image'],['selectedVideo','動画','video']] as const).map(([key,label,type])=><label key={key}>{label}<select value={item[key]||''} onChange={e=>edit({[key]:e.target.value||null})}><option value="">未選択</option>{item.assets.filter(a=>a.type===type).map(a=><option value={a.path} key={a.path}>{a.name}</option>)}</select></label>)}<div className="order-controls"><button disabled={board.items[0].id===active} onClick={()=>move(-1)}>↑ 前へ</button><button disabled={board.items.at(-1)?.id===active} onClick={()=>move(1)}>↓ 後へ</button></div><p className="inspector-help">変更は「変更を保存」で確定します。<br/>順番を変えても素材との対応は保持されます。</p></>:<p>構成項目を選択してください。</p>}</aside></div>}
<footer className="timeline"><button className="play-button" disabled={!board.items.length} onClick={()=>{setPlayIndex(0);setPlaying(true)}} aria-label="簡易再生を開始">▶</button><div className="timeline-label">簡易再生<small>未定の尺は仮に3秒</small></div><div className="timeline-items">{board.items.map((x,n)=><button key={x.id} className={active===x.id?'current':''} onClick={()=>{setActive(x.id);setMode('storyboard')}}><span>{String(n+1).padStart(2,'0')} {x.title}</span><small>{x.durationSeconds===null?'未定':x.durationSeconds+'s'}</small></button>)}</div></footer></div>
{(doc||viewer||playing)&&<div className="modal-backdrop" onClick={()=>{setDoc(null);setViewer(null);setPlaying(false)}}><section className="modal" role="dialog" aria-modal="true" aria-label={doc?.title||'素材プレビュー'} onClick={e=>e.stopPropagation()}><button className="modal-close" autoFocus onClick={()=>{setDoc(null);setViewer(null);setPlaying(false)}}>閉じる ×</button>{doc?<><h2>{doc.title}</h2><div className="markdown">{md(doc.markdown,doc.path)}</div></>:viewer?<><h2>{'label'in viewer?viewer.label:viewer.name}</h2>{viewer.type==='image'?<img className="full-image" src={file(viewer.path)} alt={'label'in viewer?viewer.label:viewer.name}/>:<video className="full-image" src={file(viewer.path)} controls autoPlay/>}</>:preview?<><p className="eyebrow">簡易再生 · {playIndex+1} / {board.items.length}</p><h2>{preview.title}</h2><p>{preview.durationSeconds===null?'予定尺未定：プレビュー用に3秒表示（保存されません）':preview.durationSeconds+'秒'}</p>{preview.selectedVideo?<video key={preview.id} className="full-image" src={file(preview.selectedVideo)} autoPlay controls/>:preview.selectedStart?<div className="preview-images"><img src={file(preview.selectedStart)} alt="開始画像"/>{preview.selectedEnd&&<img src={file(preview.selectedEnd)} alt="終了画像"/>}</div>:<div className="empty-state">{preview.notes||'画像未選択'}</div>}</>:null}</section></div>}
{history&&<div className="modal-backdrop"><section className="modal history" role="dialog" aria-modal="true" aria-label="保存履歴"><button autoFocus className="modal-close" onClick={()=>setHistory(null)}>閉じる ×</button><h2>保存履歴</h2><p>保存前の状態へ戻せます。</p>{!history.length&&<p>履歴はまだありません。</p>}{history.map(h=><div className="history-entry" key={h.id}><span>{h.createdAt}</span><button onClick={()=>ask('この履歴へ復元しますか？現在の保存済み状態は履歴に残ります。未保存の変更は失われます。',async()=>{try{await api('/api/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:board.revision,id:h.id})});await load();setHistory(null);setMessage('履歴を復元しました')}catch(e){setError(String(e));setHistory(null)}})}>復元</button></div>)}</section></div>}
{confirmAction&&<div className="modal-backdrop confirm-layer"><section className="modal history" role="dialog" aria-modal="true" aria-label="操作の確認"><h2>操作の確認</h2><p>{confirmText}</p><div className="order-controls"><button onClick={()=>setConfirmAction(null)}>キャンセル</button><button className="primary" onClick={()=>{const action=confirmAction;setConfirmAction(null);action()}}>実行する</button></div></section></div>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
